# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.SYS_ORCH_GITHUB }}
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/apps/grafana-proxy"
    registries:
      - github
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[gomod] "
  - package-ecosystem: "gomod"
    directories:
      - "/apps/orch-otelcol/o11y-otel-contextprocessor/otelcol-dev/contextprocessor"
    registries:
      - github
    schedule:
      interval: daily
    groups:
      orch-otelcol:
        patterns:
          - "*"  # In this case, it's good to bump dependencies in one PR, so group all updates into a single larger pull request.
    commit-message:
      prefix: "[gomod] "
  - package-ecosystem: "github-actions"
    directory: "/"
    registries:
      - github
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[gha] "
  - package-ecosystem: "docker"
    directories:
      - "/apps/grafana-proxy"
      - "/apps/orch-otelcol"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[docker] "
