{
 "title": "Orchestrator Pod List",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pods Not Running",
   "type": "stat",
   "description": "Displays number of pods currently unable to run",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"}) "
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Running'})"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "Orchestrator Pods",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "kube_pod_status_phase==1", "legendFormat": "__auto" },
    { "expr": "kube_pod_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}