{
 "title": "Orchestrator Node",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "instance_addr",
    "label": "Instance",
    "query": {
     "query": "label_values(kube_node_info{node=\"$instance\"},instance)"
    }
   },
   { "name": "resolution", "query": "30s,1m,3m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "Node Ready",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{node=\"$instance\",condition=\"Ready\",status=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{node=\"$instance\",condition=\"MemoryPressure\",status=\"false\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"DiskPressure\", node=\"$instance\", status=\"false\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pid Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{node=\"$instance\", condition=\"PIDPressure\", status=\"false\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"$instance\"}"
    },
    {
     "expr": "kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"}==1",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(k8s_node_cpu_usage{k8s_node_name=\"$instance\"})/sum(k8s_node_allocatable_cpu{k8s_node_name=\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_node_memory_working_set{k8s_node_name=\"$instance\"}) / sum(k8s_node_allocatable_memory{k8s_node_name=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod List",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "List of Pods on $instance",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "kube_pod_info{node=\"$instance\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "kube_pod_status_phase{instance=\"$instance_addr\"}==1",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_replace(label_replace((sum(container_cpu_usage{k8s_node_name=\"$instance\"}) by (k8s_pod_name,k8s_namespace_name))*1000,\"pod\",\"$1\",\"k8s_pod_name\",\"(.*)\"),\"namespace\",\"$1\",\"k8s_namespace_name\",\"(.*)\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_replace(label_replace((sum(container_memory_working_set{k8s_node_name=\"$instance\"}) by (k8s_pod_name,k8s_namespace_name)),\"pod\",\"$1\",\"k8s_pod_name\",\"(.*)\"),\"namespace\",\"$1\",\"k8s_namespace_name\",\"(.*)\")",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Not Running",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "kube_pod_info{node=\"$instance\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"}==1",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(k8s_node_cpu_usage{k8s_node_name=\"$instance\"})/sum(k8s_node_allocatable_cpu{k8s_node_name=\"$instance\"})",
       "legendFormat": "$instance"
      }
     ]
    },
    {
     "title": "CPU(millicores) by Namespace",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(k8s_pod_cpu_usage{k8s_node_name=\"$instance\"}*1000) by (k8s_namespace_name) ",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(k8s_node_memory_working_set{k8s_node_name=\"$instance\"}) / sum(k8s_node_allocatable_memory{k8s_node_name=\"$instance\"})",
       "legendFormat": "Memory Usage %"
      }
     ]
    },
    {
     "title": "Memory Usage by Namespace",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(k8s_pod_memory_working_set{k8s_node_name=\"$instance\"}) by (k8s_namespace_name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage (GB)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "k8s_node_filesystem_capacity{k8s_node_name=\"$instance\"}",
       "legendFormat": "Capacity"
      },
      {
       "expr": "k8s_node_filesystem_usage{k8s_node_name=\"$instance\"}",
       "legendFormat": "Disk Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(k8s_node_network_io{direction=\"receive\",k8s_node_name=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Total Received Bytes"
      },
      {
       "expr": "-sum(rate(k8s_node_network_io{direction=\"transmit\",k8s_node_name=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Total transmitted bytes"
      }
     ]
    },
    {
     "title": "Packets dropped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum(rate(k8s_node_network_errors{direction=\"receive\",k8s_node_name=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Packets dropped (receive)"
      },
      {
       "expr": "-sum(rate(k8s_node_network_errors{direction=\"transmit\",k8s_node_name=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Packets dropped (transmit)"
      }
     ]
    }
   ]
  }
 ]
}