{
 "title": "Pod Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{clusterName=\"\",namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   { "name": "resolution", "query": "30s,1m,3m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{pod=\"$pod\",namespace=\"$namespace\"} == 1",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pod Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod IP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{pod_ip}}"
    }
   ]
  },
  {
   "title": "Running On Node",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Created By",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{created_by_kind}}"
    }
   ]
  },
  {
   "title": "Pod containers",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(k8s_container_cpu_request{k8s_namespace_name=\"$namespace\", k8s_pod_name=\"$pod\"}*1000,\"container\",\"$1\",\"k8s_container_name\",\"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(k8s_container_cpu_limit{k8s_namespace_name=\"$namespace\", k8s_pod_name=\"$pod\"}*1000,\"container\",\"$1\",\"k8s_container_name\",\"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(k8s_container_memory_request{k8s_namespace_name=\"$namespace\", k8s_pod_name=\"$pod\"},\"container\",\"$1\",\"k8s_container_name\",\"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(k8s_container_memory_limit{k8s_namespace_name=\"$namespace\", k8s_pod_name=\"$pod\"},\"container\",\"$1\",\"k8s_container_name\",\"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod CPU usage [mCores]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(container_cpu_usage{k8s_pod_name=\"$pod\",k8s_namespace_name=\"$namespace\"}*1000)",
       "legendFormat": "$pod"
      }
     ]
    },
    {
     "title": "Pod memory usage ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set{k8s_namespace_name=\"$namespace\", k8s_pod_name=\"$pod\"})",
       "legendFormat": "$pod"
      }
     ]
    },
    {
     "title": "Containers CPU usage [mCores]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "container_cpu_usage{k8s_pod_name=\"$pod\",k8s_namespace_name=\"$namespace\"}*1000",
       "legendFormat": "{{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Containers memory usage ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set{k8s_namespace_name=\"$namespace\", k8s_pod_name=\"$pod\"}) by (k8s_container_name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}