{
 "title": "Orchestrator Cluster",
 "description": "Edge Orchestrator Cluster View",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "resolution", "query": "30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "Nodes Ready",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})/ count(kube_node_info)) == 1 OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"false\"})/ count(kube_node_info)) == 1 OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"false\"})/ count(kube_node_info)) == 1 OR on() vector(0)"
    }
   ]
  },
  {
   "title": "PID Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(kube_node_status_condition{condition=\"PIDPressure\",status=\"false\"})/ count(kube_node_info)) == 1 OR on() vector(0)"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(k8s_node_cpu_utilization)/sum(k8s_node_allocatable_cpu))",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"}) / sum(k8s_node_allocatable_cpu)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"}) / sum(k8s_node_allocatable_cpu)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(k8s_node_memory_working_set) / sum(k8s_node_allocatable_memory))",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"}) / sum(k8s_node_allocatable_memory)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"}) / sum(k8s_node_allocatable_memory)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes Ready",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{})"
    }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"}) "
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Running'})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(k8s_node_cpu_utilization)", "legendFormat": "Usage" },
    { "expr": "sum(k8s_node_allocatable_cpu)", "legendFormat": "Total" },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(k8s_node_memory_working_set)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(k8s_node_allocatable_memory)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "StatefulSets Down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_replicas{}) - sum(kube_statefulset_status_replicas_ready{})"
    }
   ]
  },
  {
   "title": "StatefulSets Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_replicas{})"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Cluster Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_node_info) by (instance, node, os_image, internal_ip,kernel_version)",
     "legendFormat": "_auto"
    },
    {
     "expr": "sum without (k8s_node_name) (label_replace((sum(k8s_node_cpu_utilization) by(k8s_node_name) /sum(k8s_node_allocatable_cpu) by (k8s_node_name))*100,\"node\",\"$1\",\"k8s_node_name\",\"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum without (k8s_node_name) (label_replace((sum(k8s_node_memory_working_set) by (k8s_node_name) / sum(k8s_node_allocatable_memory) by (k8s_node_name))*100,\"node\",\"$1\",\"k8s_node_name\",\"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_node_status_condition{condition=\"Ready\",status=\"true\"}) by (node)",
     "legendFormat": "Ready"
    },
    {
     "expr": "max(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"}) by (node)",
     "legendFormat": "Memory Pressure"
    },
    {
     "expr": "max(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"}) by (node)",
     "legendFormat": "DiskPressure"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(sum(k8s_node_cpu_utilization)/sum(k8s_node_allocatable_cpu))",
       "legendFormat": "CPU usage in %"
      }
     ]
    },
    {
     "title": "CPU Utilization by instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(k8s_node_cpu_utilization) by (k8s_node_name) /sum(k8s_node_allocatable_cpu) by (k8s_node_name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(sum(k8s_node_memory_working_set) / sum(k8s_node_allocatable_memory))",
       "legendFormat": "Memory usage in %"
      }
     ]
    },
    {
     "title": "Memory Utilization by instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(k8s_node_memory_working_set) by (k8s_node_name) / sum(k8s_node_allocatable_memory) by (k8s_node_name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Network Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(k8s_node_network_io{direction=\"receive\"}[$__rate_interval]))",
       "legendFormat": "Total Received Bytes"
      },
      {
       "expr": "-sum(rate(k8s_node_network_io{direction=\"transmit\"}[$__rate_interval]))",
       "legendFormat": "Total transmitted bytes"
      }
     ]
    },
    {
     "title": "Network Utilization by instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(k8s_node_network_io{direction=\"receive\"}[$__rate_interval])) by (k8s_node_name)",
       "legendFormat": "{{k8s_node_name}} received bytes"
      },
      {
       "expr": "-sum(rate(k8s_node_network_io{direction=\"transmit\"}[$__rate_interval])) by (k8s_node_name)",
       "legendFormat": "{{k8s_node_name}} transmitted bytes"
      }
     ]
    },
    {
     "title": "Network Saturation - Packets dropped",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(k8s_node_network_errors{direction=\"receive\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "-sum(rate(k8s_node_network_errors{direction=\"trams,ot\"}[$__rate_interval]))",
       "legendFormat": "Packets dropped (transmit)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(k8s_node_filesystem_capacity{})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(k8s_node_filesystem_usage{})",
       "legendFormat": "Disk Usage"
      }
     ]
    },
    {
     "title": "Disk Usage by instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "k8s_node_filesystem_usage{}/k8s_node_filesystem_capacity{}",
       "legendFormat": "{{k8s_node_name}} Capacity"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes Resource Count",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(kube_namespace_labels)", "legendFormat": "Namespaces" },
      {
       "expr": "sum(kube_pod_container_status_running)",
       "legendFormat": "Running Containers"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase='Running'})",
       "legendFormat": "Running Pods"
      },
      { "expr": "sum(kube_service_info)", "legendFormat": "Services" },
      { "expr": "sum(kube_endpoint_info)", "legendFormat": "Endpoints" },
      { "expr": "sum(kube_ingress_info)", "legendFormat": "Ingresses" },
      { "expr": "sum(kube_deployment_labels{})", "legendFormat": "Deployments" },
      { "expr": "sum(kube_statefulset_labels{})", "legendFormat": "Statefulsets" },
      { "expr": "sum(kube_daemonset_labels{})", "legendFormat": "Daemonsets" },
      {
       "expr": "sum(kube_persistentvolumeclaim_info{})",
       "legendFormat": "Persistent Volume Claims"
      },
      { "expr": "sum(kube_hpa_labels{})", "legendFormat": "Horizontal Pod Autoscalers" },
      { "expr": "sum(kube_configmap_info{})", "legendFormat": "Configmaps" },
      { "expr": "sum(kube_secret_info{})", "legendFormat": "Secrets" },
      {
       "expr": "sum(kube_networkpolicy_labels{})",
       "legendFormat": "Network Policies"
      },
      {
       "expr": "count(up{job=\"node-exporter\"})",
       "legendFormat": "Nodes"
      }
     ]
    }
   ]
  }
 ]
}