# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
  ".cache/**",
  "ci/**",
  "**/*.json",
  "deployments/edgenode-observability/templates/*.tpl",
  "VERSION"
]
SPDX-FileCopyrightText = "2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"