{
 "title": "EdgeNode / Pods",
 "description": "Edgenode pods dashboard",
 "tags": [ "cluster" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "projectName",
    "label": "Project",
    "query": {
     "query": "label_values(project_metadata,projectName)"
    }
   },
   {
    "name": "projectId",
    "label": "ProjectID",
    "query": {
     "query": "label_values(project_metadata{projectName=\"$projectName\"},projectId)"
    }
   },
   {
    "name": "hostId",
    "label": "Host",
    "query": {
     "query": "edge_host_status{projectId=\"$projectId\"}"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{projectId=\"$projectId\", node=\"$hostId\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", node=\"$hostId\", projectId=\"$projectId\"},pod)"
    }
   },
   { "name": "resolution", "label": "Resolution", "query": "30s, 1m, 3m, 5m" },
   {
    "name": "guid",
    "query": {
     "query": "label_values(edge_host_status{hostID=\"$hostId\", projectId=\"$projectId\"},deviceGuid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Created by",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"$hostId\",namespace=\"$namespace\", pod=~\"$pod\", projectId=\"$projectId\"}",
     "legendFormat": "{{ created_by_kind }}:{{ created_by_name }}"
    }
   ]
  },
  {
   "title": "Running on",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"$hostId\",namespace=\"$namespace\", pod=~\"$pod\", projectId=\"$projectId\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Pod IP Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"$hostId\",namespace=\"$namespace\", pod=~\"$pod\", projectId=\"$projectId\"}",
     "legendFormat": "{{ pod_ip }}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Pod Containers",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by(__tenant_id__, cluserName, node, namespace, pod, container) ({__name__=~\"kube_pod_container.+\", pod != \"\", container != \"\", namespace=\"$namespace\", pod=~\"$pod\", node=\"$hostId\", projectId=\"$projectId\"}) > bool -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=\"$hostId\",namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"POD\", container!=\"\", projectId=\"$projectId\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{node=\"$hostId\",namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"POD\", container!=\"\", projectId=\"$projectId\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Network - Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{node=\"$hostId\",namespace=\"$namespace\", pod=~\"$pod\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{node=\"$hostId\",namespace=\"$namespace\", pod=~\"$pod\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network - Packets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{node=\"$hostId\",namespace=\"$namespace\", pod=~\"$pod\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_total{node=\"$hostId\",namespace=\"$namespace\", pod=~\"$pod\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network - Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{node=\"$hostId\",namespace=\"$namespace\", pod=~\"$pod\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_dropped_total{node=\"$hostId\",namespace=\"$namespace\", pod=~\"$pod\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network - Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{node=\"$hostId\",namespace=\"$namespace\", pod=~\"$pod\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_errors_total{node=\"$hostId\",namespace=\"$namespace\", pod=~\"$pod\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Last 100 Lines",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{source=~\"edgenode_container_logs|edgenode_application_logs\", pod=~\"$pod\", projectId=\"$projectId\"}",
     "maxLines": 100
    }
   ]
  }
 ]
}