{
 "title": "Virtual Machines",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "projectName",
    "label": "Project",
    "query": {
     "query": "label_values(project_metadata,projectName)"
    }
   },
   {
    "name": "projectId",
    "label": "ProjectID",
    "query": {
     "query": "label_values(project_metadata{projectName=\"$projectName\"},projectId)"
    }
   },
   {
    "name": "hostId",
    "label": "Host",
    "query": {
     "query": "edge_host_status{projectId=\"$projectId\"}"
    }
   },
   {
    "name": "deployment",
    "label": "Namespace",
    "query": {
     "query": "label_values(kubevirt_vmi_vcpu_seconds_total{instance=\"$hostId\", projectId=\"$projectId\"},exported_namespace)"
    }
   },
   {
    "name": "application",
    "label": "User Application",
    "query": {
     "query": "label_values(kubevirt_vmi_memory_resident_bytes{node=\"$hostId\", projectId=\"$projectId\"},name)"
    }
   },
   { "name": "resolution", "label": "Resolution", "query": "30s, 1m, 3m, 5m" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kubevirt_vmi_memory_resident_bytes{node=\"$hostId\", projectId=\"$projectId\"},exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<center>${application}</center>\n"
   }
  },
  {
   "title": "Percent Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kubevirt_vmi_memory_available_bytes{node=\"$hostId\", name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}-kubevirt_vmi_memory_usable_bytes{node=\"$hostId\", name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"})/kubevirt_vmi_memory_available_bytes{node=\"$hostId\", name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_filesystem_used_bytes{node=\"$hostId\",name=\"$application\", disk_name!~\"loop.+\", exported_namespace=\"$deployment\", projectId=\"$projectId\"} / 1024 / 1024 / 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Diskspace",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_filesystem_capacity_bytes{node=\"$hostId\",name=\"$application\",  disk_name!~\"loop.+\", exported_namespace=\"$deployment\", projectId=\"$projectId\"} / 1024 / 1024 / 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "description": "Amount of time in running status",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kubevirt_vm_running_status_last_transition_timestamp_seconds{exported_namespace=\"$deployment\", name=\"$application\", projectId=\"$projectId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": {
    "content": "<center>${deployment}</center>\n"
   }
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "The total number of rx packets dropped on vNIC interfaces.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(kubevirt_vmi_memory_available_bytes{node=\"$hostId\", name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}-kubevirt_vmi_memory_usable_bytes{node=\"$hostId\", name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"})/kubevirt_vmi_memory_available_bytes{node=\"$hostId\", name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Disk Usage (GB)",
   "type": "timeseries",
   "description": "Disk Usage in GB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "kubevirt_vmi_filesystem_used_bytes{node=\"$hostId\",name=\"$application\", disk_name!~\"loop.+\", exported_namespace=\"$deployment\", projectId=\"$projectId\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{disk_name}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Storage Read/Write (Bytes)",
   "type": "timeseries",
   "description": "Total number of written and read bytes from storage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kubevirt_vmi_storage_read_traffic_bytes_total{node=\"$hostId\",name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "- sum(rate(kubevirt_vmi_storage_write_traffic_bytes_total{node=\"$hostId\",name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Storage Read/Write Times (s)",
   "type": "timeseries",
   "description": "Total time (s) spent on read/write operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(kubevirt_vmi_storage_read_times_seconds_total{node=\"$hostId\", exported_namespace=\"$deployment\", kubernetes_vmi_label_app=\"$application\", projectId=\"$projectId\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "- rate(kubevirt_vmi_storage_write_times_seconds_total{node=\"$hostId\", exported_namespace=\"$deployment\", kubernetes_vmi_label_app=\"$application\", projectId=\"$projectId\"}[$__rate_interval])",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Network usage (packet/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(kubevirt_vmi_network_receive_packets_total{node=\"$hostId\",name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(kubevirt_vmi_network_transmit_packets_total{node=\"$hostId\",name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Network usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kubevirt_vmi_network_receive_bytes_total{node=\"$hostId\",name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(kubevirt_vmi_network_transmit_bytes_total{node=\"$hostaID\",name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(kubevirt_vmi_network_receive_errors_total{node=\"$hostId\",name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(kubevirt_vmi_network_transmit_errors_total{node=\"$hostId\",name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(kubevirt_vmi_network_receive_errors_total{node=\"$hostId\",name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(kubevirt_vmi_network_transmit_errors_total{node=\"$hostId\",name=\"$application\", exported_namespace=\"$deployment\", projectId=\"$projectId\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}