{
 "title": "Edge Node Cluster",
 "tags": [ "cluster" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "projectName",
    "label": "Project",
    "query": {
     "query": "label_values(project_metadata,projectName)"
    }
   },
   {
    "name": "projectId",
    "label": "ProjectID",
    "query": {
     "query": "label_values(project_metadata{projectName=\"$projectName\"},projectId)"
    }
   },
   {
    "name": "hostId",
    "label": "Host",
    "query": {
     "query": "edge_host_status{projectId=\"$projectId\"}"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_info{node=\"$hostId\", projectId=\"$projectId\"},clusterName)"
    }
   },
   {
    "name": "node",
    "label": "Edge Node",
    "query": {
     "query": "label_values(kube_node_info{clusterName=\"edgeNode\", projectId=\"$projectId\"},node)"
    }
   },
   { "name": "resolution", "label": "Resolution", "query": "30s, 1m, 3m, 5m" },
   {
    "name": "clusterName",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_time_seconds{instance=\"$hostId\", projectId=\"$projectId\"},clusterName)"
    }
   },
   {
    "name": "guid",
    "query": {
     "query": "label_values(edge_host_status{hostID=\"$hostId\"},deviceGuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$hostId\", instance!=\"\", projectId=\"$projectId\"}",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Nodes in Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{clusterName=\"$clusterName\",projectId=\"$projectId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods on node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{clusterName=\"$clusterName\",projectId=\"$projectId\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$hostId\", instance!=\"\", projectId=\"$projectId\"} - node_boot_time_seconds{instance=\"$hostId\", instance!=\"\", projectId=\"$projectId\"}"
    }
   ]
  },
  {
   "title": "Nodes in Cluster",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kube_node_info{clusterName=\"$clusterName\",projectId=\"$projectId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace((edge_host_status{name!=\"\"}==1 > 0 ),\"system_uuid\",\"$1\",\"deviceGuid\",\"(.+)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Pods",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{clusterName=\"$clusterName\",projectId=\"$projectId\"}==1"
    },
    {
     "expr": "kube_pod_info{clusterName=\"$clusterName\",projectId=\"$projectId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{clusterName=\"$clusterName\",projectId=\"$projectId\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{clusterName=\"$clusterName\", image!=\"\", projectId=\"$projectId\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployed Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployed Containers",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{clusterName=\"$clusterName\", namespace!~\"akri|cattle-fleet-system|calico-system|calico-fleet-system|calico-impersonation-system|cattle-system|cdi|edge-system|kube-node-lease|kube-public|kube-system|kubevirt|local|metallb-system|observability|openebs|sriov-network-operator|tigera-operator|cert-manager|istio-operator|storageos|gatekeeper-system|nfd|orchestrator-system\", projectId=\"$projectId\"}==1"
      },
      {
       "expr": "kube_pod_info{clusterName=\"$clusterName\", namespace!~\"akri|cattle-fleet-system|calico-system|calico-fleet-system|calico-impersonation-system|cattle-system|cdi|edge-system|kube-node-lease|kube-public|kube-system|kubevirt|local|metallb-system|observability|openebs|sriov-network-operator|tigera-operator|cert-manager|istio-operator|storageos|gatekeeper-system|nfd|orchestrator-system\", projectId=\"$projectId\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Deployed Virtual Machines",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "kubevirt_vmi_memory_resident_bytes{clusterName=\"$clusterName\",projectId=\"$projectId\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "node_load1{clusterName=\"$clusterName\",projectId=\"$projectId\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{clusterName=\"$clusterName\",projectId=\"$projectId\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{clusterName=\"$clusterName\",projectId=\"$projectId\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "Context Switches & Interrupts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "rate(node_context_switches_total{clusterName=\"$clusterName\",projectId=\"$projectId\"}[$__rate_interval])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "rate(node_intr_total{clusterName=\"$clusterName\",projectId=\"$projectId\"}[$__rate_interval])",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "node_filefd_maximum{clusterName=\"$clusterName\",projectId=\"$projectId\"}",
       "legendFormat": "Maximum file descriptors"
      },
      {
       "expr": "node_filefd_allocated{clusterName=\"$clusterName\",projectId=\"$projectId\"}",
       "legendFormat": "Allocated file descriptors"
      }
     ]
    },
    {
     "title": "Time Sync",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{clusterName=\"$clusterName\",projectId=\"$projectId\"}",
       "legendFormat": "Estimated error in seconds"
      },
      {
       "expr": "node_timex_maxerror_seconds{clusterName=\"$clusterName\",projectId=\"$projectId\"}",
       "legendFormat": "Maximum error in seconds"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network usage (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{clusterName=\"$clusterName\",projectId=\"$projectId\"}[$__rate_interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "- sum(rate(node_network_transmit_bytes_total{clusterName=\"$clusterName\",projectId=\"$projectId\"}[$__rate_interval]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Network errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_errs_total{clusterName=\"$clusterName\",projectId=\"$projectId\"}[$__rate_interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "- sum(rate(node_network_transmit_errs_total{clusterName=\"$clusterName\",projectId=\"$projectId\"}[$__rate_interval]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Network usage (packet/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_packets_total{clusterName=\"$clusterName\",projectId=\"$projectId\"}[$__rate_interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "- sum(rate(node_network_transmit_packets_total{clusterName=\"$clusterName\",projectId=\"$projectId\"}[$__rate_interval]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Network total drops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_drop_total{clusterName=\"$clusterName\",projectId=\"$projectId\"}[$__rate_interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "- sum(rate(node_network_transmit_drop_total{clusterName=\"$clusterName\",projectId=\"$projectId\"}[$__rate_interval]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "TCP Currently Established",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{clusterName=\"$clusterName\",projectId=\"$projectId\"}",
       "legendFormat": "TCP Currently Established"
      }
     ]
    },
    {
     "title": "NF Conntrack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{clusterName=\"$clusterName\",projectId=\"$projectId\"}",
       "legendFormat": "NF Conntrack entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{clusterName=\"$clusterName\",projectId=\"$projectId\"}",
       "legendFormat": "NF Conntrack limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistent Volumes - Usage in %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{clusterName=\"$clusterName\",projectId=\"$projectId\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes{clusterName=\"$clusterName\",projectId=\"$projectId\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    },
    {
     "title": "Persistent Volumes - Usage in GB",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{clusterName=\"$clusterName\",projectId=\"$projectId\"}) by (persistentvolumeclaim)"
      },
      {
       "expr": "sum(kubelet_volume_stats_capacity_bytes{clusterName=\"$clusterName\",projectId=\"$projectId\"}) by (persistentvolumeclaim) "
      }
     ]
    },
    {
     "title": "Persistent Volumes - Inodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_inodes_used{clusterName=\"$clusterName\",projectId=\"$projectId\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_inodes{clusterName=\"$clusterName\",projectId=\"$projectId\"}) by (persistentvolumeclaim) * 100",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Unhealthy Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Waiting Pods",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 140 },
     "targets": [
      {
       "expr": "kube_pod_container_status_waiting_reason *on(instance) group_left(node) kube_node_info{node=\"$hostId\", projectId=\"$projectId\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}