{
 "title": "Edge Node Host Performance",
 "tags": [ "metrics" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "projectName",
    "label": "Project",
    "query": {
     "query": "label_values(project_metadata,projectName)"
    }
   },
   {
    "name": "projectId",
    "label": "ProjectID",
    "query": {
     "query": "label_values(project_metadata{projectName=\"$projectName\"},projectId)"
    }
   },
   {
    "name": "hostId",
    "label": "Host",
    "query": {
     "query": "edge_host_status{deviceGuid !=\"\", projectId=\"$projectId\"}"
    }
   },
   {
    "name": "guid",
    "label": "Host",
    "query": {
     "query": "label_values(edge_host_status{hostID=\"$hostId\", projectId=\"$projectId\"},deviceGuid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "edge_host_status{hostID=\"$hostId\",projectId=\"$projectId\"} == 1"
    }
   ]
  },
  {
   "title": "Provisioning Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "edge_host_provisioning_status{hostID=\"$hostId\",projectId=\"$projectId\"} == 1"
    }
   ]
  },
  {
   "title": "Onboarding Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "edge_host_onboarding_status{hostID=\"$hostId\",projectId=\"$projectId\"} == 1"
    }
   ]
  },
  {
   "title": "Update Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "edge_host_update_status{hostID=\"$hostId\",projectId=\"$projectId\"} == 1"
    }
   ]
  },
  {
   "title": "Under Maintenance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (projectId, hostID) (edge_host_schedule{hostID=\"$hostId\",projectId=\"$projectId\"})"
    }
   ]
  },
  {
   "title": "Host ID (Display Name)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (projectId, hostID, name) (edge_host_status{hostID=\"$hostId\", projectId=\"$projectId\", name!=\"\", name!=\"$hostId\"})",
     "legendFormat": "{{hostID}} ({{name}})"
    },
    {
     "expr": "sum by (projectId, hostID, name) (edge_host_status{hostID=\"$hostId\", projectId=\"$projectId\", name=\"$hostId\"})",
     "legendFormat": "{{hostID}}"
    },
    {
     "expr": "sum by (projectId, hostID, name) (edge_host_status{hostID=\"$hostId\", projectId=\"$projectId\", name=\"\"})",
     "legendFormat": "{{hostID}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(100-cpu_usage_idle{host=\"$hostId\", cpu=\"cpu-total\",projectId=\"$projectId\"})*100)/100"
    }
   ]
  },
  {
   "title": "Total CPUs/Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cpu_usage_idle{host=\"$hostId\",cpu!~\"cpu-.+\",projectId=\"$projectId\"})"
    }
   ]
  },
  {
   "title": "Core Temperature",
   "type": "stat",
   "description": "Max and average temperature from given time range",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(temp_temp{sensor=~\".+(core|cpu).+\", host=\"$hostId\",projectId=\"$projectId\"}[$__range]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(temp_temp{sensor=~\".+(core|cpu).+\", host=\"$hostId\",projectId=\"$projectId\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "System UUID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "edge_host_status{hostID=\"$hostId\",projectId=\"$projectId\"} == 1",
     "legendFormat": "{{deviceGuid}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(100-cpu_usage_idle{host=\"$hostId\", cpu=\"cpu-total\",projectId=\"$projectId\"})*100)/100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mem_total{host=\"$hostId\",projectId=\"$projectId\"}"
    }
   ]
  },
  {
   "title": "Serial",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "edge_host_schedule{hostID=\"$hostId\", serial!=\"\",projectId=\"$projectId\"}",
     "legendFormat": "{{serial}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_uptime{host=\"$hostId\",host!=\"\",projectId=\"$projectId\"}"
    }
   ]
  },
  {
   "title": "Provisioning Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "edge_host_total_provisioning_time{hostID=\"$hostId\",projectId=\"$projectId\"}"
    }
   ]
  },
  {
   "title": "Total Disk Used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceil((1-sum(execdiskmetrics_disk_size_available_bytes{host=\"$hostId\",projectId=\"$projectId\"})/sum(execdiskmetrics_disk_size_total_bytes{host=\"$hostId\",projectId=\"$projectId\"}))*10000))/10000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "stat",
   "description": "Sum of all disks on device",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(execdiskmetrics_disk_size_total_bytes{host=\"$hostId\",projectId=\"$projectId\"})"
    }
   ]
  },
  { "title": "Host Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Host statuses history",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (hostID,status) (edge_host_status{hostID=\"$hostId\", projectId=\"$projectId\"} == 1)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum by (hostID,provisioningStatus) (edge_host_provisioning_status{hostID=\"$hostId\", projectId=\"$projectId\"}==1)",
     "legendFormat": "Provisioned"
    },
    {
     "expr": "sum by (hostID,onboardingStatus) (edge_host_onboarding_status{hostID=\"$hostId\", projectId=\"$projectId\"} == 1)",
     "legendFormat": "Onboarded"
    },
    {
     "expr": "sum by (hostID,updateStatus) (edge_host_update_status{hostID=\"$hostId\", projectId=\"$projectId\"} ==1)",
     "legendFormat": "No new updates available"
    },
    {
     "expr": "sum by (hostID) (edge_host_schedule{hostID=\"$hostId\", projectId=\"$projectId\"})",
     "legendFormat": "Maintenance"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_usage_user{host=\"$hostId\", cpu=\"cpu-total\",projectId=\"$projectId\"}",
       "legendFormat": "User"
      },
      {
       "expr": "cpu_usage_system{host=\"$hostId\", cpu=\"cpu-total\",projectId=\"$projectId\"}",
       "legendFormat": "System"
      },
      {
       "expr": "sum(100-cpu_usage_idle{host=\"$hostId\", cpu=\"cpu-total\",projectId=\"$projectId\"})",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mem_available{host=\"$hostId\",projectId=\"$projectId\"}",
       "legendFormat": "mem_available"
      },
      {
       "expr": "mem_free{host=\"$hostId\",projectId=\"$projectId\"}",
       "legendFormat": "mem_free"
      },
      {
       "expr": "swap_used{host=~\"$hostId\",projectId=\"$projectId\"}",
       "legendFormat": "mem_swap"
      },
      {
       "expr": "mem_used{host=\"$hostId\",projectId=\"$projectId\"}",
       "legendFormat": "mem_used"
      },
      {
       "expr": "mem_buffered{host=~\"$hostId\",projectId=\"$projectId\"}",
       "legendFormat": "mem_buffered"
      },
      {
       "expr": "mem_cached{host=~\"$hostId\",projectId=\"$projectId\"}",
       "legendFormat": "mem_cached"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "-rate(net_bytes_recv{host=\"$hostId\",interface!~\"(cali.+|lo)\",projectId=\"$projectId\"}[$__range])",
       "legendFormat": "received by the {{interface}}"
      },
      {
       "expr": "rate(net_bytes_sent{host=\"$hostId\",interface!~\"(cali.+|lo)\",projectId=\"$projectId\"}[$__range])",
       "legendFormat": "sent by the {{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg(temp_temp{sensor=~\".+(core|cpu).+\", host=\"$hostId\",projectId=\"$projectId\"})",
       "legendFormat": "Average Core Temperature"
      },
      {
       "expr": "max(temp_temp{sensor=~\".+(core|cpu).+\", host=\"$hostId\",projectId=\"$projectId\"})",
       "legendFormat": "Max Core Temperature"
      }
     ]
    }
   ]
  },
  {
   "title": "Block devices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disks Usages",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "disk_used_percent{host=~\"$hostId\",projectId=\"$projectId\"}",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Disk IO Reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(diskio_read_bytes{host=~\"$hostId\",name!~\"dm-[0-9]|loop.+\",projectId=\"$projectId\"}[5m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk IO Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(diskio_write_bytes{host=~\"$hostId\",name!~\"dm-[0-9]|loop.+\",projectId=\"$projectId\"}[5m])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*execdiskmetrics_disk_size_used_partition_bytes{host=\"$hostId\",projectId=\"$projectId\"} / execdiskmetrics_disk_size_total_bytes{host=\"$hostId\",projectId=\"$projectId\"} ",
       "legendFormat": "__auto"
      },
      {
       "expr": "100* execdiskmetrics_disk_size_used_lvm_bytes{host=\"$hostId\",projectId=\"$projectId\"} / execdiskmetrics_disk_size_total_bytes{host=\"$hostId\",projectId=\"$projectId\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total disk bytes",
     "type": "timeseries",
     "description": "Total size of each disk on the edge node in bytes. Detected by the lsblk command.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "execdiskmetrics_disk_size_total_bytes{host=\"$hostId\",projectId=\"$projectId\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total used LVM bytes",
     "type": "timeseries",
     "description": "Total amount of space on each disk assigned to LVMs in bytes. Detected by the lsblk command.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "execdiskmetrics_disk_size_used_lvm_bytes{host=\"$hostId\", device_name!=\"\",projectId=\"$projectId\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total disk available bytes",
     "type": "timeseries",
     "description": "Total available bytes on each disk. Determined from the difference between the total disk size and the total amount of the disk in use in the partitions and assigned to LVMs.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "execdiskmetrics_disk_size_available_bytes{host=\"$hostId\",projectId=\"$projectId\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total used bytes",
     "type": "timeseries",
     "description": "Total amount of space in use across all partitions on each disk in bytes. Detected by the df command.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "execdiskmetrics_disk_size_used_partition_bytes{host=\"$hostId\",projectId=\"$projectId\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}