# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: edgenode-observability
description: Edge Node Centralized Observability
type: application
version: 0.10.26
appVersion: 0.10.26
annotations:
  revision: faf693d2b08fe66aee0314bc0219af40d0c295d7
  created: "2026-04-14T10:39:56Z"
dependencies:
  - name: minio
    alias: minio
    version: "5.4.0"
    repository: https://charts.min.io/
    condition: import.minio.enabled
  - name: mimir-distributed
    condition: import.mimir.enabled
    version: "6.0.6"
    repository: "https://grafana.github.io/helm-charts"
  - name: loki
    condition: import.loki.enabled
    version: "14.2.0"
    repository: "https://grafana-community.github.io/helm-charts"
  - name: opentelemetry-operator
    condition: import.otel-operator.enabled
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    version: "0.113.1"
  - name: opentelemetry-collector
    condition: import.otel.enabled
    version: "0.155.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  - name: grafana
    alias: grafana
    version: "12.3.2"
    repository: "https://grafana-community.github.io/helm-charts"
    condition: import.grafana.enabled
