# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: orchestrator-observability
description: Orchestrator centralized observability
type: application
version: 0.5.20
appVersion: 0.5.20
annotations:
  revision: f42659c2c5cbf1675b5b017fa3d1b0f1a4aac233
  created: "2026-04-01T13:36:53Z"
dependencies:
  - name: loki
    condition: import.loki.enabled
    version: "6.53.0"
    repository: "https://grafana.github.io/helm-charts"
  - name: opentelemetry-collector
    alias: opentelemetry-collector-daemonset
    condition: import.otel.enabled
    version: "0.146.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  - name: opentelemetry-collector
    condition: import.otel.enabled
    version: "0.146.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  - name: minio
    alias: minio
    version: "5.4.0"
    repository: https://charts.min.io/
    condition: import.minio.enabled
  - name: mimir-distributed
    condition: import.mimir.enabled
    version: "6.0.5"
    repository: "https://grafana.github.io/helm-charts"
  - name: grafana
    alias: grafana
    version: "11.1.8"
    repository: "https://grafana-community.github.io/helm-charts"
    condition: import.grafana.enabled
  - name: tempo
    condition: import.tempo.enabled
    version: "1.26.4"
    repository: "https://grafana-community.github.io/helm-charts"
