# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Pre-Merge CI Pipeline

on:
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

permissions: {}

jobs:
  pre-checks:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      all_changed_projects: ${{ steps.merge-changed-projects.outputs.all_changed_projects }}
    steps:
      - name: "Check out repository code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Git safe directory"
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: "Verify Branch Name"
        uses: open-edge-platform/orch-ci/verify-branch-name@ee6d75f0a0762112d5521b59ff4d971dbe3f3cfb # 0.1.36

      - name: "Discover Changed Subfolders Inside 'apps'"
        id: discover-changes-apps
        uses: open-edge-platform/orch-ci/discover-changed-subfolders@ee6d75f0a0762112d5521b59ff4d971dbe3f3cfb # 0.1.36
        with:
          project_folder: "./apps"

      - name: "Discover Changed Subfolders Inside 'charts'"
        id: discover-changes-charts
        uses: open-edge-platform/orch-ci/discover-changed-subfolders@ee6d75f0a0762112d5521b59ff4d971dbe3f3cfb # 0.1.36
        with:
          project_folder: "./charts"
          
      - name: "Merge Changed Subfolders"
        id: merge-changed-projects
        env:
          APPS_CHANGED_PROJECTS: ${{ steps.discover-changes-apps.outputs.changed_projects }}
          CHARTS_CHANGED_PROJECTS: ${{ steps.discover-changes-charts.outputs.changed_projects }}
        run: |
          # TODO: Is there a better way to merge the two arrays in GHA?
          echo "Changed Projects in apps: $APPS_CHANGED_PROJECTS"
          echo "Changed Projects in charts: $CHARTS_CHANGED_PROJECTS"

          # Merge the two arrays (add 'apps/' and 'charts/') and remove empty strings (if any)
          all_changed_projects=$(jq -c -n --argjson a "$APPS_CHANGED_PROJECTS" --argjson b "$CHARTS_CHANGED_PROJECTS" '
            ($a | map(select(. != "") | "apps/" + .)) +
            ($b | map(select(. != "") | "charts/" + .))
          ')
          echo "all_changed_projects=$all_changed_projects" >> $GITHUB_OUTPUT
          echo "All Changed Projects: $all_changed_projects"
  pre-merge:
    permissions:
      contents: write
    needs: pre-checks
    # Only run the pipeline if there are changes in the projects (matrix -> project_folder will fail with empty array)
    if: ${{ needs.pre-checks.outputs.all_changed_projects != '' && toJson(fromJson(needs.pre-checks.outputs.all_changed_projects)) != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        project_folder: ${{ fromJson(needs.pre-checks.outputs.all_changed_projects) }}
    uses: open-edge-platform/orch-ci/.github/workflows/pre-merge.yml@ee6d75f0a0762112d5521b59ff4d971dbe3f3cfb # 0.1.36
    with:
      project_folder: ${{ matrix.project_folder }}
      prefix_tag_separator: "-"
      run_reuse_check: true
      run_version_check: true
      bootstrap_tools: "go,gotools,nodejs,python,golangci-lint2,helm,shellcheck,hadolint,yq,jq,protolint"
      run_dep_version_check: false
      cache_go: true
      run_build: true
      run_lint: true
      run_test: true
      remove_cache_go: true
      run_validate_clean_folder: false
      run_docker_build: true
      run_helm_build: true
      run_artifact: false
  final-check:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [pre-merge]
    steps:
      - name: Final Status Check
        env:
          PRE_MERGE_PIPELINE_RESULT: ${{ needs.pre-merge.result }}
        run: |
          echo "Pre-merge pipeline result: $PRE_MERGE_PIPELINE_RESULT"

          if [ "$PRE_MERGE_PIPELINE_RESULT" == "success" ] || [ "$PRE_MERGE_PIPELINE_RESULT" == "skipped" ]; then
            echo "Pre-merge check passed successfully."
          else
            echo "Pre-merge checks failed. PR can't get merged"
            exit 1
          fi
