# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Pre-Merge CI Pipeline

on:
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

permissions: {}

jobs:
  pre-checks:
    permissions:
      contents: read
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-ubuntu-latest' || 'ubuntu-latest' }}
    outputs:
      all_changed_projects: ${{ steps.merge-changed-projects.outputs.all_changed_projects }}
    steps:
      - name: "Check out repository code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: "Git safe directory"
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: "Verify Branch Name"
        uses: open-edge-platform/orch-ci/verify-branch-name@0.1.1

      - name: "Discover Changed Subfolders Inside 'apps'"
        id: discover-changes-apps
        uses: open-edge-platform/orch-ci/discover-changed-subfolders@0.1.1
        with:
          project_folder: "./apps"

      - name: "Discover Changed Subfolders Inside 'charts'"
        id: discover-changes-charts
        uses: open-edge-platform/orch-ci/discover-changed-subfolders@0.1.1
        with:
          project_folder: "./charts"
          
      - name: "Merge Changed Subfolders"
        id: merge-changed-projects
        run: |
          # TODO: Is there a better way to merge the two arrays in GHA?
          apps_changed_projects='${{ steps.discover-changes-apps.outputs.changed_projects }}'
          charts_changed_projects='${{ steps.discover-changes-charts.outputs.changed_projects }}'
          echo "Changed Projects in apps: $apps_changed_projects"
          echo "Changed Projects in charts: $charts_changed_projects"

          # Merge the two arrays (add 'apps/' and 'charts/') and remove empty strings (if any)
          all_changed_projects=$(jq -c -n --argjson a "$apps_changed_projects" --argjson b "$charts_changed_projects" '
            ($a | map(select(. != "") | "apps/" + .)) +
            ($b | map(select(. != "") | "charts/" + .))
          ')
          echo "all_changed_projects=$all_changed_projects" >> $GITHUB_OUTPUT
          echo "All Changed Projects: $all_changed_projects"
  pre-merge:
    permissions:
      contents: write
    needs: pre-checks
    # Only run the pipeline if there are changes in the projects (matrix -> project_folder will fail with empty array)
    if: ${{ needs.pre-checks.outputs.all_changed_projects != '' && toJson(fromJson(needs.pre-checks.outputs.all_changed_projects)) != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        project_folder: ${{ fromJson(needs.pre-checks.outputs.all_changed_projects) }}
    uses: open-edge-platform/orch-ci/.github/workflows/pre-merge.yml@main
    with:
      run_reuse_check: true
      run_version_check: true
      run_security_scans: true
      run_dep_version_check: true
      cache_go: true
      run_build: true
      run_lint: true
      run_test: true
      run_validate_clean_folder: false
      run_docker_build: true
      run_helm_build: true
      run_scan_containers: true
      run_artifact: false
      prefix_tag_separator: "-"
      project_folder: ${{ matrix.project_folder }}
      bootstrap_tools: "go,gotools,nodejs,python,golang-lint,helm,shellcheck,hadolint,yq,jq,protolint"
    secrets: inherit
